### ISSUE TITLE
Clean Configuration in code provided

### ISSUE THREAD

**Issue by pitchmuc** [fooku18/pythonPowerBI#1]
Hello, in your getData script, some of the configuration is available.
We may want to clean that.

**Comment by fooku18** [comment]
Hi @pitchmuc,
thank you for your comment. I left this file in as a quick reference as otherwise the repo would have been pretty much not understandable. Anyway, I changed the setup and included an empty config file and a - hopefully - detailed readme for the app. Thank you for being attentive :)
